### ISSUE TITLE
Video tutorial regarding using the addon

### ISSUE THREAD

**Issue by HarshEcka** [FrandSX/sxtools-blender#3]
I know you have created the documentation but somehow I am not able to replicate the results from you documentation..So kindly make a indepth tutorial of the addon or update the documentation with easy to follow gif images...Also if possible give an insight how the I can use the same for realistic skin approach using the addon.

**Comment by FrandSX** [comment]
Hi there,

I understand that videos and gifs are popular methods for documenting things, and I have long been tempted to make some. However, SX Tools has gone through UI changes at a fairly steady pace, and any video materials would be obsolete by now.

As for questions with specific use cases, I’ve experimentally opened the new Github Discussions feature for this purpose. Let’s see how it turns out.
