### ISSUE TITLE
Layers issue

### ISSUE THREAD

**Issue by SinyavtsevIlya** [FrandSX/sxtools-blender#4]
@FrandSX  
Hey! Thank you for sharing such a great tool!
I'm a game developer, and we are using a very similar pipeline. 
I carefully read the documentation, and tried to get the layers feature to work, but unfortunately faced some issues:

1) When I add several layers, in `Full Shading` mode i only can see the latest created layer
2) Merging two layers doesn't seem to work for me. If the top layer is set to, let's say, `multiply` and the bottom one is `additive` then after pressing `merge down` the first layer information is cleared and the seconds layer is not changed.
3) If I drag the opacity slider, blender decides to change the shading mode to `Material preview`

I tried both `3.1.2` and `2.9` versions to make it work with no success.

**Comment by FrandSX** [comment]
Hi there!
1) Please clarify what you mean by adding layers. The number of layers on the object is defined at setup, with the PBR mode initializing the mesh with a 7-2-1-PBR setup. (Seven color layers, two gradient layers, one overlay and then PBR material channels). If you mean only a single color layer is displayed, that should happen when SX Tools is set to Debug mode.

2) One admittedly counterintuitive element is that Layer 1 is the _bottom_ layer, and 2-7 are each above the previous one in the stack. When you merge from a multiply layer onto a layer below, did the additive layer have color under the multiply layer? Multiplying a transparent area with any color will just result in a transparent area. If the layer being merged into is, for example, fully white, and the layer above has some verts or faces filled with red, the resulting merge will be a mostly white layer where parts of it were multiplied to red. If both layers are set to Alpha mode, the opacity of both layers is preserved. Aside from the layer stack being upside down, the results should be similar to what happens if you apply layers in 2D paint programs.

3) SX Tools creates a custom material to display the layered vertex colors in Blender viewport. It's necessary to be in Material Preview (or Rendered) mode for Full Shading to be correctly displayed. Opacity changes should be correctly displayed in Full Shading / Material Preview.

**Comment by SinyavtsevIlya** [comment]
> One admittedly counterintuitive element is that Layer 1 is the bottom layer, and 2-7 are each above the previous one in the stack. 
Oh boy, that explains everything! I feel like I was holding a book upside down. 
Now all problems are gone. That was a bit unexpected though.
Thanks!
